config/routes.rb
Depot::Application.routes.draw do
  get 'admin', to: "admin#index"

  controller :sessions do
    get 'login', to: :new
    post 'login', to: :create
    delete 'logout', to: :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items do
      get :decrement_quantity, on: :member
    end
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: "store#index", as: 'store'
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items, dependent: :destroy

  def add_product(product_id, product_price)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id, price: product_price)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:edit, :update, :destroy]
  skip_before_filter :authorize, only: [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access a nonexistent cart #{params[:id]}"
      redirect_to store_url, notice: "A nonexistent cart"
    else
      respond_to do |format|
        format.html
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title"><%= t('carts.cart.title') %></div>
<table>
  <tr>
    <td colspan="4" class="sum_of_price">Sum</td>
  </tr>
  <%= render(cart.line_items) %>
  <tr class="total_line">
    <td></td>
    <td colspan="2"><%= t('carts.cart.total') %>></td>
    <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
  </tr>
</table>
<%= button_to t('carts.cart.checkout'), new_order_path, method: :get %>
<%= button_to t('carts.cart.empty'), cart, method: :delete, data: {confirm: t('carts.cart.confirm')} %>

app/views/carts/_cart_store.html.erb
<div class="cart_title"><%= t('carts.cart.title') %></div>
<table>
  <% @cart.line_items.each do |f| %>
    <% if f == @current_item %>
      <tr id="current_item">
    <% else %>
      <tr>
    <% end %>
    <td><%= link_to "-", decrement_quantity_line_item_path(f) %></td>
    <td><%= f.quantity %> &times;</td>
    <td><%= f.product.title %></td>
    <td class="item_price"><%= number_to_currency(f.total_price) %></td>
    </tr>
  <% end %>
  <tr class="total_line">
    <td colspan="3"><%= t('carts.cart.total') %></td>
    <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
  </tr>
</table>
<%= button_to t('carts.cart.checkout'), new_order_path, method: :get, class: "checkout" %>
<%= button_to t('carts.cart.empty'), @cart, method: :delete, data: {confirm: t('carts.cart.confirm')} %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<%= render @cart %>