config/routes.rb
Depot::Application.routes.draw do
  get 'admin', to: "admin#index"

  controller :sessions do
    get 'login', to: :new
    post 'login', to: :create
    delete 'logout', to: :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items do
      get :decrement_quantity, on: :member
    end
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: "store#index", as: 'store'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <%= form_tag store_path, method: :get, class: 'locale' do %>
      <%= select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    <%= image_tag("logo.png", size: "100x50") %>
    <%= @page_title || t('layouts.application.title') %>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hiden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render "/carts/cart_store", object: @cart %>
        <% end %>
      <% end %>

      <ul>
        <li class="time">Now is <%= Time.now %></li>
        <li></li>
        <li><%= link_to t('layouts.application.home'), store_path %></li>
        <li><%= link_to t('layouts.application.questions'), "#" %></li>
        <li><%= link_to t('layouts.application.news'), "#" %></li>
        <li><%= link_to t('layouts.application.contact'), "#" %></li>
      </ul>

      <% if session[:user_id] %>
        <ul>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Orders", orders_path %></li>
          <li><%= link_to "Users", users_path %></li>
        </ul>
        <%= button_to "Logout", logout_path, method: :delete %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>